/******************************************************************************/
/****                           Tables and Views                           ****/
/******************************************************************************/

CREATE TABLE ALUGUEL (
	ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    LIVRO_ID INTEGER NOT NULL,
    DATA_ALUGUEL DATE NOT NULL,
    PERIODO INTEGER NOT NULL);


CREATE TABLE AUTOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CIDADE_ID INTEGER NOT NULL);


CREATE TABLE CIDADE (
    ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL);


CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CIDADE_ID INTEGER NOT NULL);


CREATE TABLE EDITORA (
    ID INTEGER NOT NULL,
    NOME INTEGER NOT NULL,
    CIDADE_ID INTEGER NOT NULL);


CREATE TABLE FUNCIONARIO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    CIDADE_ID INTEGER NOT NULL);


CREATE TABLE LIVRO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    ANO_PUBLICACAO INTEGER NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    AUTOR_ID INTEGER NOT NULL,
    EDITORA_ID INTEGER NOT NULL);


/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/


ALTER TABLE AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY (ID);
ALTER TABLE CIDADE ADD CONSTRAINT PK_CIDADE PRIMARY KEY (ID);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID);
ALTER TABLE EDITORA ADD CONSTRAINT PK_EDITORA PRIMARY KEY (ID);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);
ALTER TABLE LIVRO ADD CONSTRAINT PK_LIVRO PRIMARY KEY (ID);
ALTER TABLE ALUGUEL ADD CONSTRAINT PK_ALUGUEL PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/


ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);
ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_LIVRO FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID);
ALTER TABLE AUTOR ADD CONSTRAINT FK_AUTOR_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
ALTER TABLE EDITORA ADD CONSTRAINT FK_EDITORA_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_CIADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_AUTOR FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR (ID);
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_EDITORA FOREIGN KEY (EDITORA_ID) REFERENCES EDITORA (ID);


